### ISSUE TITLE
Remove setuptools-scm

### ISSUE THREAD

**Issue by ktbarrett** [ktbarrett/find_libpython#41]
Overall it's pretty mid.

**Comment by phansel** [comment]
Is it illegal to hardcode package __version__ these days?

**Comment by ktbarrett** [comment]
@phansel No, but it's repeating the same information in two places that can get out of sync. It's better to either have a single source of truth (usually the `package/_version.py` file, which is loaded into `setup.py`, [see here](https://github.com/ktbarrett/kuddl/blob/1c8a3e436e7c38de82c3aaaec72463f54afd43bb/setup.py#L7-L10)) or have it repeated but introduce a check to ensure they are the same (perhaps as a pre-commit hook). I just need to dedicate 5 minutes to the task 😆.

**Comment by ktbarrett** [comment]
Will release 0.3.1 soon after getting CI back up and running.

**Comment by ktbarrett** [comment]
0.3.1 released!
