### ISSUE TITLE
Source tarball missing on pypi for 0.3.1

### ISSUE THREAD

**Issue by heerener** [ktbarrett/find_libpython#43]
I'm not sure whether it's intentional, but the last source tarball on pypi is 0.3.0 - could you add one for 0.3.1 as well please?

**Comment by ktbarrett** [comment]
This was intentional, but I uploaded a source tarball now. Just curious, why a source tarball?

**Comment by heerener** [comment]
Thank you!

I've created a [spack package](https://github.com/spack/spack/pull/42804) for it (one of our packages depends on it, other people might find it useful too) and they generally prefer source tarballs. Now I can add 0.3.1 as well.
