### ISSUE TITLE
find_libpython was not able to find a libpython in the current Python environment

### ISSUE THREAD

**Issue by mounikakallakola1** [ktbarrett/find_libpython#53]
I am new to cocotb and facing a similar issue as
**find_libpython was not able to find a libpython in the current Python environment. Ensure
the Python development packages are installed. If they are installed and find_libpython
is not finding the path to libpython, file an upstream bug in find_libpython; then
manually override the LIBPYTHON_LOC make variable with the absolute path to libpython.so
(or python.dll on Windows).
. Stop.
**

I have the following environment setup
Python 3.7.2
pip 24.0

Package              Version

cocotb                 1.8.1
find_libpython     0.4.0
pip                       24.0
setuptools           40.6.2

and PATH is set with <.....>/venv/bin

cocotb-config --lib-dir has some path but cocotb-config --libpython does not give me any path.Also i donot see any libpython.so installed in my virtual environment

Can you please help me to overcome this issue?

**Comment by ktbarrett** [comment]
Okay, what OS? What environment are you using?

**Comment by mounikakallakola1** [comment]
I have changed my python version and now it works fine. Thank you very much for the support
